// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwDqud9-kqKgJhX89RgFGDwP-99SVkAg',
    appId: '1:376140322642:web:b1c4d1ae005cad9a3f8c8b',
    messagingSenderId: '376140322642',
    projectId: 'imela-pos',
    authDomain: 'imela-pos.firebaseapp.com',
    storageBucket: 'imela-pos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJQiP1KHVaLEYCwT-4KQ5M1-dt32Z2Z4',
    appId: '1:376140322642:android:f9975e41e007c75b3f8c8b',
    messagingSenderId: '376140322642',
    projectId: 'imela-pos',
    storageBucket: 'imela-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Rai1tApfz0EKyC3IVrHikMMBO40NNjw',
    appId: '1:376140322642:ios:e01c24348a740c2a3f8c8b',
    messagingSenderId: '376140322642',
    projectId: 'imela-pos',
    storageBucket: 'imela-pos.appspot.com',
    iosBundleId: 'com.imela.pos.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Rai1tApfz0EKyC3IVrHikMMBO40NNjw',
    appId: '1:376140322642:ios:f52e88cf4d68dda13f8c8b',
    messagingSenderId: '376140322642',
    projectId: 'imela-pos',
    storageBucket: 'imela-pos.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFwDqud9-kqKgJhX89RgFGDwP-99SVkAg',
    appId: '1:376140322642:web:11defdd2a42bc9183f8c8b',
    messagingSenderId: '376140322642',
    projectId: 'imela-pos',
    authDomain: 'imela-pos.firebaseapp.com',
    storageBucket: 'imela-pos.appspot.com',
  );
}
