name: imela_ui_kit
description: UI design factory and reusable ui componenets accross the app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  localization: ^2.1.0
  intl: ^0.19.0
  collection: ^1.14.13
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.6
  page_transition: ^2.1.0

  modal_bottom_sheet: ^3.0.0
  bottom_sheet: ^4.0.4

  flutter_staggered_grid_view: 0.7.0
  pin_code_fields: 8.0.1
  smooth_page_indicator: 1.1.0

  flutter_animate: ^4.5.0
  slide_countdown: ^1.6.1

  auto_size_text_field: ^2.2.3
  auto_size_text: ^3.0.0

  shimmer: ^3.0.0
  flash: ^3.1.1
  badges: ^3.1.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
