// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyz7DYrlkFC-fCJApCm7SCoXfxbYlE28',
    appId: '1:78981459340:web:5902a0b1d923d811c83aa9',
    messagingSenderId: '78981459340',
    projectId: 'imela-consumer-app',
    authDomain: 'imela-consumer-app.firebaseapp.com',
    storageBucket: 'imela-consumer-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3cOHpYwFgoIpCDtjAFR4rBZYhp4HNjcE',
    appId: '1:78981459340:android:ac38402e544e412ec83aa9',
    messagingSenderId: '78981459340',
    projectId: 'imela-consumer-app',
    storageBucket: 'imela-consumer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVd5XDKVV5K0TmznvClUaqy6F51wvYkRw',
    appId: '1:78981459340:ios:5c66420c5042ce9cc83aa9',
    messagingSenderId: '78981459340',
    projectId: 'imela-consumer-app',
    storageBucket: 'imela-consumer-app.appspot.com',
    iosBundleId: 'com.imela.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVd5XDKVV5K0TmznvClUaqy6F51wvYkRw',
    appId: '1:78981459340:ios:5c66420c5042ce9cc83aa9',
    messagingSenderId: '78981459340',
    projectId: 'imela-consumer-app',
    storageBucket: 'imela-consumer-app.appspot.com',
    iosBundleId: 'com.imela.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyz7DYrlkFC-fCJApCm7SCoXfxbYlE28',
    appId: '1:78981459340:web:16cf474e74c29431c83aa9',
    messagingSenderId: '78981459340',
    projectId: 'imela-consumer-app',
    authDomain: 'imela-consumer-app.firebaseapp.com',
    storageBucket: 'imela-consumer-app.appspot.com',
  );

}