name: imela_core
description: Core module
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.13

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_crashlytics: ^4.1.0

  get_it: ^7.7.0
  # get: ^4.6.6

  injectable: ^2.4.2
  dartx: ^1.2.0

  # local packages
  imela_utils: ^0.1.0
  imela_data: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.2.0

  json_serializable: ^6.8.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
