name: imela_admin
description: Imela customer app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  localization: ^2.1.0
  intl: ^0.19.0
  collection: ^1.14.13
  jwt_decode: ^0.3.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0

  go_router: ^13.2.5
  page_transition: ^2.1.0
  get_it: ^7.7.0

  get: ^4.6.6
  freezed_annotation: ^2.4.1
  injectable: ^2.4.2

  # url_launcher: 6.2.5
  # url_launcher_android: 6.3.0
  # url_launcher_ios: 6.2.5
  # url_launcher_platform_interface: 2.3.2

  mask_text_input_formatter: 2.4.0

  flutter_animate: ^4.5.0
  dartx: ^1.2.0

  # local packages
  imela_core: ^0.1.0
  imela_ui_kit: ^0.1.0
  imela_data: ^0.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.12
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  generate: true
